Algoritmo "INTERVALO ENTRE OS NÚMEROS"

Var
     numero : inteiro


Inicio
       escreva("Digite Um Número " )
       leia(numero)
       se numero >= 100 entao
       se numero <= 200   entao
       escreva("Numero esta entre 100 e 200 ")
       senao

       
       escreva("O número não está no intervalo entre 100 e 200")
       fimse
       senao


   escreval("O número não está no intervalo entre 100 e 200")
fimse
       
       
       


Fimalgoritmo