Algoritmo "Numero Maior"

Var

   num1 , num2: inteiro

Inicio
       escreva("Digite um Valor = " )
       leia(num1)
       escreva("Digite um Valor = " )
         leia(num2)
       se  num1 > num2 entao
     escreva("O primeiro número ",num1," é maior que o segundo",num2)
      senao
     escreva("O segundo número",num2," é maior que o primeiro",num1)
      fimse



Fimalgoritmo