Algoritmo "soma, subtração, multiplicação e a divisão dos números"

Var
nu1 , nu2 : inteiro

Inicio
        escreva("digite um numero : " )
        leia(nu1)
        escreva("digite um numero : " )
        leia(nu2)
        escreva(" a soma é : " , nu1+nu2)
        escreva(" a subtração é : " , nu1-nu2)
        escreva(" a multiplicação é : " , nu1*nu2)
        escreva(" a divisão é : " , nu1/nu2)


Fimalgoritmo