Algoritmo "troca"

Var
     valor1 , valor2 , troca : inteiro


Inicio
          escreva( " digite valor1 = " )
          leia(valor1)
          escreva( " digite valor2 = " )
          leia(valor2)
          troca <- valor1
          valor1 <- valor2
          valor2 <- troca
          
          escreva( " novo valor1 = " , valor1 )
           escreva( "  novo valor2 = " ,  valor2  )
          

          
          


Fimalgoritmo